// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ialsjgxwmmpiedzejbrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhbHNqZ3h3bW1waWVkemVqYnJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NDIzMzcsImV4cCI6MjA2NTExODMzN30.6cDvu3CN_giTlrYOA9CmlceA8uX2B-SLkombd-SKdqs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);